### ISSUE TITLE
Websockets tests have become flakey on Travis CI

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#1569]
We now often see [these tests](
https://github.com/thelounge/lounge/blob/90ae5dbefc3a5864e11d200e3c9fa905e0dab0e6/test/server.js#L37-L104) fail on Travis, with the following failures:

```
  1) Uncaught error outside test suite
[...]
    WebSockets
      2) should emit authorized message
      3) should create network
      4) should emit init message
```

<details>
<summary>Failure details</summary>

```
  1)  Uncaught error outside test suite:
     Uncaught Error: Vapid private key should be 32 bytes long when decoded.
      at Object.validatePrivateKey (node_modules/web-push/src/vapid-helper.js:88:11)
      at Object.WebPushLib.setVapidDetails (node_modules/web-push/src/web-push-lib.js:60:17)
      at new WebPush (src/plugins/webpush.js:33:14)
      at ClientManager.init (src/clientManager.js:19:17)
      at Identification (src/server.js:152:12)
      at new Identification (src/identification.js:36:4)
      at Server.server.listen (src/server.js:151:3)
      at emitListeningNT (net.js:1370:10)
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
      at startup (bootstrap_node.js:201:16)
      at bootstrap_node.js:626:3
  2) Server WebSockets should emit authorized message:
     Uncaught TypeError: Cannot read property 'vapidKeys' of undefined
      at sendInitEvent (src/server.js:412:41)
      at initializeClient (src/server.js:437:3)
      at finalInit (src/server.js:445:26)
      at initClient (src/server.js:452:11)
      at Socket.performAuthentication (src/server.js:471:3)
      at Namespace.sockets.on (src/server.js:139:27)
      at Namespace.emit (node_modules/socket.io/lib/namespace.js:209:10)
      at node_modules/socket.io/lib/namespace.js:176:14
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)
  3) Server WebSockets should create network:
     Uncaught TypeError: Cannot read property 'vapidKeys' of undefined
      at sendInitEvent (src/server.js:412:41)
      at initializeClient (src/server.js:437:3)
      at finalInit (src/server.js:445:26)
      at initClient (src/server.js:452:11)
      at Socket.performAuthentication (src/server.js:471:3)
      at Namespace.sockets.on (src/server.js:139:27)
      at Namespace.emit (node_modules/socket.io/lib/namespace.js:209:10)
      at node_modules/socket.io/lib/namespace.js:176:14
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)
  4) Server WebSockets should emit init message:
     Uncaught TypeError: Cannot read property 'vapidKeys' of undefined
      at sendInitEvent (src/server.js:412:41)
      at initializeClient (src/server.js:437:3)
      at finalInit (src/server.js:445:26)
      at initClient (src/server.js:452:11)
      at Socket.performAuthentication (src/server.js:471:3)
      at Namespace.sockets.on (src/server.js:139:27)
      at Namespace.emit (node_modules/socket.io/lib/namespace.js:209:10)
      at node_modules/socket.io/lib/namespace.js:176:14
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```
</details>

As far as I could tell, these failures started to happen after https://github.com/thelounge/lounge/pull/1124 got merged.
@xPaw, do you have an idea about this?

**Comment by xPaw** [comment]
I have a feeling vapid keys are failing to generate (not enough entropy on travis?) and causes the tests to fail. Maybe we just need to add a vapid keys file with some keys to fix it.
