### ISSUE TITLE
Thelounge crashes | systemd Error: ENOENT client/themes

### ISSUE THREAD

**Issue by Thumpxr** [thelounge/lounge#1586]
Hey,

running latest Lounge version. I cant reproduce the crash, it just happens.

systemd service running lounge

Error in jounalctl -u thelounge

```
Sep 29 12:54:33 server lounge[966]: Error: ENOENT: no such file or directory, scandir 'client/themes/'
Sep 29 12:54:33 server lounge[966]:     at Object.fs.readdirSync (fs.js:911:18)
Sep 29 12:54:33 server lounge[966]:     at index (/usr/lib/node_modules/thelounge/src/server.js:150:19)
Sep 29 12:54:33 server lounge[966]:     at Layer.handle [as handle_request] (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/layer.js:95:5)
Sep 29 12:54:33 server lounge[966]:     at trim_prefix (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:317:13)
Sep 29 12:54:33 server lounge[966]:     at /usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:284:7
Sep 29 12:54:33 server lounge[966]:     at Function.process_params (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:335:12)
Sep 29 12:54:33 server lounge[966]:     at next (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:275:10)
Sep 29 12:54:33 server lounge[966]:     at allRequests (/usr/lib/node_modules/thelounge/src/server.js:137:9)
Sep 29 12:54:33 server lounge[966]:     at Layer.handle [as handle_request] (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/layer.js:95:5)
Sep 29 12:54:33 server lounge[966]:     at trim_prefix (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:317:13)
Sep 29 18:12:47 server lounge[966]: Error: ENOENT: no such file or directory, scandir 'client/themes/'
Sep 29 18:12:47 server lounge[966]:     at Object.fs.readdirSync (fs.js:911:18)
Sep 29 18:12:47 server lounge[966]:     at index (/usr/lib/node_modules/thelounge/src/server.js:150:19)
Sep 29 18:12:47 server lounge[966]:     at Layer.handle [as handle_request] (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/layer.js:95:5)
Sep 29 18:12:47 server lounge[966]:     at trim_prefix (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:317:13)
Sep 29 18:12:47 server lounge[966]:     at /usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:284:7
Sep 29 18:12:47 server lounge[966]:     at Function.process_params (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:335:12)
Sep 29 18:12:47 server lounge[966]:     at next (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:275:10)
Sep 29 18:12:47 server lounge[966]:     at allRequests (/usr/lib/node_modules/thelounge/src/server.js:137:9)
Sep 29 18:12:47 server lounge[966]:     at Layer.handle [as handle_request] (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/layer.js:95:5)
Sep 29 18:12:47 server lounge[966]:     at trim_prefix (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:317:13)
Sep 29 18:13:45 server lounge[966]: Error: ENOENT: no such file or directory, scandir 'client/themes/'
Sep 29 18:13:45 server lounge[966]:     at Object.fs.readdirSync (fs.js:911:18)
Sep 29 18:13:45 server lounge[966]:     at index (/usr/lib/node_modules/thelounge/src/server.js:150:19)
Sep 29 18:13:45 server lounge[966]:     at Layer.handle [as handle_request] (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/layer.js:95:5)
Sep 29 18:13:45 server lounge[966]:     at trim_prefix (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:317:13)
Sep 29 18:13:45 server lounge[966]:     at /usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:284:7
Sep 29 18:13:45 server lounge[966]:     at Function.process_params (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:335:12)
Sep 29 18:13:45 server lounge[966]:     at next (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:275:10)
Sep 29 18:13:45 server lounge[966]:     at allRequests (/usr/lib/node_modules/thelounge/src/server.js:137:9)
Sep 29 18:13:45 server lounge[966]:     at Layer.handle [as handle_request] (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/layer.js:95:5)
Sep 29 18:13:45 server lounge[966]:     at trim_prefix (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:317:13)
Sep 29 18:13:46 server lounge[966]: Error: ENOENT: no such file or directory, scandir 'client/themes/'
Sep 29 18:13:46 server lounge[966]:     at Object.fs.readdirSync (fs.js:911:18)
Sep 29 18:13:46 server lounge[966]:     at index (/usr/lib/node_modules/thelounge/src/server.js:150:19)
Sep 29 18:13:46 server lounge[966]:     at Layer.handle [as handle_request] (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/layer.js:95:5)
Sep 29 18:13:46 server lounge[966]:     at trim_prefix (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:317:13)
Sep 29 18:13:46 server lounge[966]:     at /usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:284:7
Sep 29 18:13:46 server lounge[966]:     at Function.process_params (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:335:12)
Sep 29 18:13:46 server lounge[966]:     at next (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:275:10)
Sep 29 18:13:46 server lounge[966]:     at allRequests (/usr/lib/node_modules/thelounge/src/server.js:137:9)
Sep 29 18:13:46 server lounge[966]:     at Layer.handle [as handle_request] (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/layer.js:95:5)
Sep 29 18:13:46 server lounge[966]:     at trim_prefix (/usr/lib/node_modules/thelounge/node_modules/express/lib/router/index.js:317:13)

```

Said thelounge.service file of systemd:

```
[Unit]
Description=The Lounge IRC client
After=thelounge.service

[Service]
Type=simple
ExecStart=/usr/bin/lounge start
User=thelounge
Group=thelounge
Restart=on-failure
RestartSec=5
StartLimitInterval=60s
StartLimitBurst=3

[Install]
WantedBy=default.target
```

**Comment by astorije** [comment]
Closing as it was marked as `invalid`. I'm guessing you got this resolved on the IRC channel or something.
