### ISSUE TITLE
`/whowas` completely crashes The Lounge

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#213]
To reproduce it, simply type `/whowas <nick>` where nick is anyone who, for example, has left `#thelounge`. The result is the app crashes with the following stacktrace:

```js
[...]/lounge/node_modules/slate-irc/lib/plugins/whois.js:44
          map[target].server = params[2];
                             ^

TypeError: Cannot set property 'server' of undefined
    at Client.<anonymous> ([...]/lounge/node_modules/slate-irc/lib/plugins/whois.js:44:30)
    at emitOne (events.js:82:20)
    at Client.emit (events.js:169:7)
    at Client.onmessage ([...]/lounge/node_modules/slate-irc/index.js:386:8)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser.online ([...]/lounge/node_modules/slate-irc/node_modules/slate-irc-parser/index.js:88:8)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at pushData ([...]/lounge/node_modules/slate-irc/node_modules/slate-irc-parser/node_modules/linewise/lib/linewise.js:98:10)
```

Potentially an issue with slate-irc (or with how we pass it data), but still a bug.

**Comment by astorije** [comment]
FYI, when the server responds with `There was no such nickname`, the bug doesn't trigger.

**Comment by xPaw** [comment]
That's a bug in slate.

**Comment by xPaw** [comment]
#167 fixed this by getting rid of slate ;)
