### ISSUE TITLE
TypeError: Cannot read property 'close' of null

### ISSUE THREAD

**Issue by fknop** [thelounge/lounge#234]
Hi, I don't know exactly how this happened, but it crashed the process.

```
TypeError: Cannot read property 'close' of null
    at InflateRaw.Zlib.close (zlib.js:465:15)
    at PerMessageDeflate.cleanup (/usr/lib/node_modules/thelounge/node_modules/ws/lib/PerMessageDeflate.js:82:46)
    at WebSocket.cleanupWebsocketResources (/usr/lib/node_modules/thelounge/node_modules/ws/lib/WebSocket.js:957:54)
    at emitNone (events.js:85:20)
    at Socket.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)
```

**Comment by xPaw** [comment]
This is not directly related to our code. https://github.com/websockets/ws/issues/664

**Comment by xPaw** [comment]
Appears to be fixed in https://github.com/nodejs/node/pull/5982
