### ISSUE TITLE
Deprecation warning for moment().zone

### ISSUE THREAD

**Issue by deiu** [thelounge/lounge#36]
It turns out `log.js` contains a call to `moment().zone`, which is deprecated. It should use `moment().utcOffset` instead, as per https://github.com/moment/moment/issues/1779. Please stand by for PR.

```
Error
    at Moment.zone (/usr/local/lib/node_modules/thelounge/node_modules/moment/moment.js:850:105)
    at Object.module.exports.write (/usr/local/lib/node_modules/thelounge/src/log.js:19:22)
    at Client.emit (/usr/local/lib/node_modules/thelounge/src/client.js:90:9)
    at Client.<anonymous> (/usr/local/lib/node_modules/thelounge/src/plugins/irc-events/welcome.js:14:10)
    at Client.emit (events.js:129:20)
    at Client.<anonymous> (/usr/local/lib/node_modules/thelounge/node_modules/slate-irc/lib/plugins/welcome.js:14:11)
    at Client.emit (events.js:129:20)
    at Client.onmessage (/usr/local/lib/node_modules/thelounge/node_modules/slate-irc/index.js:386:8)
    at Parser.emit (events.js:107:17)
    at Parser.online (/usr/local/lib/node_modules/thelounge/node_modules/slate-irc-parser/index.js:88:8)
```

Update: pending PR -- https://github.com/thelounge/lounge/pull/37

**Comment by astorije** [comment]
:+1:
