### ISSUE TITLE
Crash when remote host closes socket with WEBIRC

### ISSUE THREAD

**Issue by staticfox** [thelounge/lounge#588]
Maybe this isn't an issue, however, during webirc negotiation with the IRCd, the lounge crashes if the ircd rejects and closes the socket.

e.g.

```
>> WEBIRC removed.pass thelounge removed.host removed.ip
<< ERROR :Closing Link:  by removed.network (WEBIRC not authorized from your host)
```

Results in:

```
2016-09-01 01:30:06 [INFO] The Lounge v2.0.0-pre.6 is now running on http://*:9000/ in public mode
2016-09-01 01:30:06 [INFO] Press ctrl-c to stop

2016-09-01 01:30:09 [DEBUG] [undefined (#0) on removed_in_issue (#0)] Connection.connect()
2016-09-01 01:30:09 [DEBUG] [undefined (#0) on removed_in_issue (#0)] Connection.disposeSocket() connected=false
2016-09-01 01:30:09 [DEBUG] [undefined (#0) on removed_in_issue (#0)] Connection.setEncoding() encoding=utf8
2016-09-01 01:30:09 [DEBUG] [undefined (#0) on removed_in_issue (#0)] Raw socket connected
2016-09-01 01:30:09 [DEBUG] [undefined (#0) on removed_in_issue (#0)] Socket fully connected
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:795:14)

npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! thelounge@2.0.0-pre.6 start: `node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thelounge@2.0.0-pre.6 start script 'node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thelounge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thelounge
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thelounge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/static/projects/lounge/npm-debug.log
```

And the debug.log file

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle thelounge@2.0.0-pre.6~prestart: thelounge@2.0.0-pre.6
6 silly lifecycle thelounge@2.0.0-pre.6~prestart: no script for prestart, continuing
7 info lifecycle thelounge@2.0.0-pre.6~start: thelounge@2.0.0-pre.6
8 verbose lifecycle thelounge@2.0.0-pre.6~start: unsafe-perm in lifecycle true
9 verbose lifecycle thelounge@2.0.0-pre.6~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/static/projects/lounge/node_modules/.bin:/usr/bin:/home/static/.rvm/gems/ruby-2.2.2/bin:/home/static/.rvm/gems/ruby-2.2.2@global/bin:/home/static/.rvm/rubies/ruby-2.2.2/bin:/usr/local/heroku/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/static/.rvm/bin:/home/static/.rvm/bin
10 verbose lifecycle thelounge@2.0.0-pre.6~start: CWD: /home/static/projects/lounge
11 silly lifecycle thelounge@2.0.0-pre.6~start: Args: [ '-c', 'node index' ]
12 silly lifecycle thelounge@2.0.0-pre.6~start: Returned: code: 1  signal: null
13 info lifecycle thelounge@2.0.0-pre.6~start: Failed to exec start script
14 verbose stack Error: thelounge@2.0.0-pre.6 start: `node index`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid thelounge@2.0.0-pre.6
16 verbose cwd /home/static/projects/lounge
17 error Linux 3.13.0-92-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.5.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error thelounge@2.0.0-pre.6 start: `node index`
22 error Exit status 1
23 error Failed at the thelounge@2.0.0-pre.6 start script 'node index'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the thelounge package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs thelounge
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls thelounge
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

So maybe this isn't specifically WEBIRC related, it's just how I've encountered it.

**Comment by astorije** [comment]
@maxpoulin64, want to fill in on this?
