### ISSUE TITLE
Crash on prefix lookup in names, if server doesn't provide PREFIX server option.

### ISSUE THREAD

**Issue by z0rc** [thelounge/lounge#644]
Running Node v6 and latest lounge installed via npm. I have znc bouncer connected to `irc.juggler.jp:6667`, the network codepage is ISO-2022-JP, but znc converts it to UTF-8 for clients. znc is joined to single channel `#ロシア`.

After adding connection to this znc in lounge, the lounge crashes with:
```
Sep 26 20:59:44 kourindou lounge[29495]: /usr/lib/node_modules/thelounge/src/plugins/irc-events/names.js:17
Sep 26 20:59:44 kourindou lounge[29495]:                                 user.mode = network.prefixLookup[user.mode];
Sep 26 20:59:44 kourindou lounge[29495]:                                                                 ^
Sep 26 20:59:44 kourindou lounge[29495]: TypeError: Cannot read property 'o' of undefined
Sep 26 20:59:44 kourindou lounge[29495]:     at /usr/lib/node_modules/thelounge/src/plugins/irc-events/names.js:17:37
Sep 26 20:59:44 kourindou lounge[29495]:     at arrayEach (/usr/lib/node_modules/thelounge/node_modules/lodash/lodash.js:498:11)
Sep 26 20:59:44 kourindou lounge[29495]:     at Function.forEach (/usr/lib/node_modules/thelounge/node_modules/lodash/lodash.js:8494:11)
Sep 26 20:59:44 kourindou lounge[29495]:     at IrcClient.<anonymous> (/usr/lib/node_modules/thelounge/src/plugins/irc-events/names.js:12:5)
Sep 26 20:59:44 kourindou lounge[29495]:     at emitOne (events.js:96:13)
Sep 26 20:59:44 kourindou lounge[29495]:     at IrcClient.emit (events.js:188:7)
Sep 26 20:59:44 kourindou lounge[29495]:     at /usr/lib/node_modules/thelounge/node_modules/irc-framework/src/client.js:153:20
Sep 26 20:59:44 kourindou lounge[29495]:     at next (/usr/lib/node_modules/thelounge/node_modules/middleware-handler/index.js:42:18)
Sep 26 20:59:44 kourindou lounge[29495]:     at MiddlewareHandler.handle (/usr/lib/node_modules/thelounge/node_modules/middleware-handler/index.js:64:3)
Sep 26 20:59:44 kourindou lounge[29495]:     at IrcCommandHandler.<anonymous> (/usr/lib/node_modules/thelounge/node_modules/irc-framework/src/client.js:147:34)
```

Numerous desktop and mobile clients are working just fine with this znc connection. Client <-> ZNC encoding is UTF-8, ZNC <-> Server encoding is ISO-2022-JP.

To mitigate this issue I just commented this `user.mode = network.prefixLookup[user.mode];` line. The crash is no more, but nicks with op rights are with `o` prefix, rather than with `@` prefix.

I believe, the lounge misses predefined PREFIX list, if the server doesn't return one.

**Comment by z0rc** [comment]
For comparison, this is how server connection info looks like from kvirc when connecting to this server:
```
[22:51:38] Your host is irc2.juggler.jp, running version 2.10.3+jp6
[22:51:38] This server was created Fri Oct 10 2014 at 12:58:29 JST
[22:51:38] Server irc2.juggler.jp version 2.10.3+jp6 supporting user modes 'aoOirw' and channel modes 'abeiIklmnoOpqrstv'
[22:51:38] There are 766 users and 0 services on 2 servers
[22:51:38] 1057 channels formed
[22:51:38] I have 398 clients, 0 services and 1 servers
```
And the same information snip while connecting to freenode:
```
[22:51:38] Your host is karatkievich.freenode.net[2001:5a0:3604:1:64:86:243:181/7000], running version ircd-seven-1.1.3
[22:51:38] This server was created Mon Aug 8 2016 at 19:04:08 UTC
[22:51:38] Server karatkievich.freenode.net version ircd-seven-1.1.3 supporting user modes 'DOQRSZaghilopswz' and channel modes 'CFILMPQSbcefgijklmnopqrstvz'
[22:51:38] This server supports: CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=freenode KNOCK STATUSMSG=@+ CALLERID=g :are supported by this server
[22:51:38] This server supports: CASEMAPPING=rfc1459 CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 ETRACE CPRIVMSG CNOTICE DEAF=D MONITOR=100 FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: :are supported by this server
[22:51:38] This server supports: EXTBAN=$,ajrxz WHOX CLIENTVER=3.0 SAFELIST ELIST=CTU :are supported by this server
[22:51:38] There are 142 users and 77650 invisible on 27 servers
[22:51:38] 27 IRC Operators online
[22:51:38] 48991 channels formed
[22:51:38] I have 3296 clients and 1 servers
[22:51:38] 3296 8950 Current local users 3296, max 8950
[22:51:38] 77792 89346 Current global users 77792, max 89346
[22:51:38] Highest connection count: 8951 (8950 clients) (641903 connections received)
```

**Comment by z0rc** [comment]
Hacky fix:
```diff
--- connection.js.orig  2016-09-26 21:58:33.078254377 +0000
+++ connection.js       2016-09-26 21:57:05.926230233 +0000
@@ -12,6 +12,11 @@
                text: "Network created, connecting to " + network.host + ":" + network.port + "..."
        }));
 
+       network.prefixLookup = {};
+       network.prefixLookup['o'] = '@';
+       network.prefixLookup['h'] = '%';
+       network.prefixLookup['v'] = '+';
+
        irc.on("registered", function() {
                if (network.irc.network.cap.enabled.length > 0) {
                        network.channels[0].pushMessage(client, new Msg({
```

**Comment by nornagon** [comment]
Here's telnet for irc2.juggler.jp:

```
telnet irc2.juggler.jp 6667
Trying 153.121.73.42...
Connected to irc2.juggler.jp.
Escape character is '^]'.
PASS *
NICK fooba34
NICK aeuoaeuo
USER aeuoaeuo 8 * :Faoeuaoeu
:irc2.juggler.jp 001 fooba34 :Welcome to the Internet Relay Network fooba34!~btCJ9yCSNE@50-247-91-226-static.hfc.comcastbusiness.net
:irc2.juggler.jp 002 fooba34 :Your host is irc2.juggler.jp, running version 2.10.3+jp6
:irc2.juggler.jp 003 fooba34 :This server was created Fri Oct 10 2014 at 12:58:29 JST
:irc2.juggler.jp 004 fooba34 irc2.juggler.jp 2.10.3+jp6 aoOirw abeiIklmnoOpqrstv
:irc2.juggler.jp 251 fooba34 :There are 721 users and 0 services on 2 servers
:irc2.juggler.jp 253 fooba34 1 :unknown connections
:irc2.juggler.jp 254 fooba34 1031 :channels formed
:irc2.juggler.jp 255 fooba34 :I have 386 clients, 0 services and 1 servers
:irc2.juggler.jp 375 fooba34 :- irc2.juggler.jp Message of the Day -
[...]
```

It seems the server isn't sending the [`005` message](http://www.irc.org/tech_docs/005.html), which includes the prefix mapping. From freenode:

```
:barjavel.freenode.net 004 aeuoaeuo barjavel.freenode.net ircd-seven-1.1.4 DOQRSZaghilopswz CFILMPQSbcefgijklmnopqrstvz bkloveqjfI
:barjavel.freenode.net 005 aeuoaeuo CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=freenode KNOCK STATUSMSG=@+ CALLERID=g :are supported by this server
:barjavel.freenode.net 005 aeuoaeuo CASEMAPPING=rfc1459 CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 ETRACE CPRIVMSG CNOTICE DEAF=D MONITOR=100 FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: :are supported by this server
:barjavel.freenode.net 005 aeuoaeuo EXTBAN=$,ajrxz WHOX CLIENTVER=3.0 SAFELIST ELIST=CTU :are supported by this server
```

We should probably use a default mapping if the server doesn't send one, to avoid crashing.

**Comment by MaxLeiter** [comment]
Testing with just Lounge (no ZNC). The modes display as their characters (`@` is `o`), which I think could be improved (by providing default modes), but it doesn't crash.

**Comment by astorije** [comment]
From @xPaw on the IRC channel:

> 01:30	+xPaw	That 2ch bug is lounge bug btw, not irc-fw
> 01:31	+xPaw	The fix it to also set ptefixloojup on connect or creation, as it currently dues so on receiving server options
> 01:32	+xPaw	As server never send options, it's never populated, irc-fw has defaults we can use
> 01:33	+xPaw	Basically just trigger this function on irc creation: https://github.com/thelounge/lounge/blob/master/src/plugins/irc-events/connection.js#L103
