### ISSUE TITLE
Couldn't start Lounge if LDAP server is down and when LDAP is enabled

### ISSUE THREAD

**Issue by thisisdarshan** [thelounge/lounge#667]
Couldn't start Lounge if LDAP server is down and when LDAP is enabled.  Trace log -

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.99.100:389
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! thelounge@2.0.0-rc.2 start: `node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the thelounge@2.0.0-rc.2 start script 'node index'.
npm ERR! This is most likely a problem with the thelounge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index

**Comment by astorije** [comment]
@thisisdarshan / @lindskogen, we'd love a contribution I'm sure 😄. Thanks for your report!
