### ISSUE TITLE
Getting a timeout error on a deleted connection throws unhandled error

### ISSUE THREAD

**Issue by rfilmyer** [thelounge/lounge#723]
I made a new connection, and when I got no response after 10 seconds, I deleted it. A few seconds later, the app had shut down, and when I checked the command prompt for a traceback:

```
2016-10-27 06:58:19 [INFO] The Lounge v2.1.0 is now running
2016-10-27 06:58:19 [INFO] Available on: http://localhost:9000/ in private mode
2016-10-27 06:58:19 [INFO] Press ctrl-c to stop

2016-10-27 06:58:19 [INFO] User 'roger' loaded
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 5.135.158.107:6667
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
```

Presumably this is an edge case that wasn't accounted for.

**Comment by xPaw** [comment]
We're aware of this issue and there are multiple ones open already.

**Comment by rfilmyer** [comment]
Ack, my apologies.
