### ISSUE TITLE
Receiving NAMES event on a non existing channel crashes

### ISSUE THREAD

**Issue by awalGarg** [thelounge/lounge#741]
Hi there. Lounge is awesome :)

I just had this crash though:

```
[experiments] ~ $ lounge start
2016-11-18 11:50:19 [INFO] The Lounge v2.1.0 is now running
2016-11-18 11:50:19 [INFO] Available on: http://0.0.0.0:8901/ in private mode
2016-11-18 11:50:19 [INFO] Press ctrl-c to stop

2016-11-18 11:50:19 [INFO] User 'awal' loaded
/usr/lib/node_modules/thelounge/src/plugins/irc-events/names.js:13
                chan.users = data.users.map(u => new User(u, network.prefixLookup));
                                       ^

TypeError: Cannot read property 'map' of undefined
    at IrcClient.<anonymous> (/usr/lib/node_modules/thelounge/src/plugins/irc-events/names.js:13:26)
    at emitOne (events.js:96:13)
    at IrcClient.emit (events.js:188:7)
    at /usr/lib/node_modules/thelounge/node_modules/irc-framework/src/client.js:153:20
    at next (/usr/lib/node_modules/thelounge/node_modules/middleware-handler/index.js:42:18)
    at MiddlewareHandler.handle (/usr/lib/node_modules/thelounge/node_modules/middleware-handler/index.js:64:3)
    at IrcCommandHandler.<anonymous> (/usr/lib/node_modules/thelounge/node_modules/irc-framework/src/client.js:147:34)
    at emitTwo (events.js:106:13)
    at IrcCommandHandler.emit (events.js:191:7)
    at IrcCommandHandler.emit (/usr/lib/node_modules/thelounge/node_modules/irc-framework/src/commands/handler.js:82:23)
```

The above is the entire log, after which lounge exited.

I am using the default config. This happened while I was authorizing with nickserv and joining #archlinux on freenode. I restarted lounge immediately, and everything is working fine, so can't really reproduce. I was advised to report this issue here from #thelounge irc channel.

Let me know if I should provide any more info. Thanks!

**Comment by awalGarg** [comment]
Ah btw, here are my node and npm versions:

```
[experiments] ~ $ node --version
v6.9.1
[experiments] ~ $ npm --version
3.10.8
```

**Comment by xPaw** [comment]
I can repro this by doing the following:
```
/query ashydasjodsa
/names ashydasjodsa
```

**Comment by awalGarg** [comment]
I can verify the repro method by @xPaw, and pulling the linked patch fixes the issue too. Thank you very much! :)

**Comment by astorije** [comment]
@xPaw, reminder to close this issue next time @prawnsalad cuts a release with https://github.com/kiwiirc/irc-framework/pull/69 in it (over the weekend, IIUC) and we pull it in this repo.
