### ISSUE TITLE
Clicking on a nick causes crash

### ISSUE THREAD

**Issue by bnvk** [thelounge/lounge#951]
Not sure what's going on here, but just did a fresh install of Lounge today (commit 1c96919) and whenever I click on a nick name in a channel or sidebar, the app crashes and spits out this error:

```
/home/sites/lounge/node_modules/irc-framework/src/commands/handlers/user.js:89
            cache.nick = nick;
                         ^

ReferenceError: nick is not defined
    at IrcCommandHandler.RPL_ENDOFWHOIS (/home/sites/lounge/node_modules/irc-framework/src/commands/handlers/user.js:89:26)
    at IrcCommandHandler.executeCommand (/home/sites/lounge/node_modules/irc-framework/src/commands/handler.js:62:37)
    at IrcCommandHandler.dispatch (/home/sites/lounge/node_modules/irc-framework/src/commands/handler.js:49:14)
    at /home/sites/lounge/node_modules/irc-framework/src/client.js:103:36
    at next (/home/sites/lounge/node_modules/middleware-handler/index.js:42:18)
    at MiddlewareHandler.handle (/home/sites/lounge/node_modules/middleware-handler/index.js:64:3)
    at Connection.<anonymous> (/home/sites/lounge/node_modules/irc-framework/src/client.js:97:31)
    at Connection.emit (/home/sites/lounge/node_modules/eventemitter3/index.js:130:35)
    at Connection.processReadBuffer (/home/sites/lounge/node_modules/irc-framework/src/connection.js:265:14)
    at Connection.socketLine (/home/sites/lounge/node_modules/irc-framework/src/connection.js:99:14)
```

**Comment by Raqbit** [comment]
Probably the same as #933
