### ISSUE TITLE
Auto user load may try to open non existing files and crash as a result

### ISSUE THREAD

**Issue by Thumpxr** [thelounge/lounge#961]
2017-03-03 17:21:25 [ERROR] Failed to read user config { Error: ENOENT: no such file or directory, open '/home/thelounge/.lounge/users/.Thumper.swp.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at ClientManager.readUserConfig (/usr/lib/node_modules/thelounge/src/clientManager.js:148:16)
    at ClientManager.loadUser (/usr/lib/node_modules/thelounge/src/clientManager.js:55:15)
    at _.difference.forEach.name (/usr/lib/node_modules/thelounge/src/clientManager.js:38:59)
    at Array.forEach (native)
    at FSWatcher.fs.watch._.debounce (/usr/lib/node_modules/thelounge/src/clientManager.js:38:38)
    at invokeFunc (/usr/lib/node_modules/thelounge/node_modules/lodash/lodash.js:10350:23)
    at trailingEdge (/usr/lib/node_modules/thelounge/node_modules/lodash/lodash.js:10397:18)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/thelounge/.lounge/users/.Thumper.swp.json' }
2017-03-04 04:10:05 [WARN] Autoloading users is now always enabled. Please remove the autoload option from your configuration file.

**Comment by tttttx2** [comment]
maybe User error? doesn't nano/vi create the Thumper.swp.json file upon editing Thumper.json? Maybe that file didn't get deleted correctly before starting the lounge?

Can not confirm the issue here. Have just updated without any problems

**Comment by vectr0n** [comment]
I am also running into the same error.

**Comment by MaxLeiter** [comment]
No problem here; does `lounge config` work?

**Comment by vectr0n** [comment]
@MaxLeiter that works ok for me

**Comment by maxpoulin64** [comment]
`.Thumper.swp.json` that's usually a vim swap file or something. That file shouldn't be there.

**Comment by vectr0n** [comment]
I don't have those files

$ ls -lha .lounge/users/
total 16K
drwxr-xr-x 2 lounge lounge 4.0K Mar 13 15:15 .
drwxr-xr-x 3 lounge lounge 4.0K Mar 13 15:10 ..
-rw-r--r-- 1 lounge lounge 3.0K Mar  8 14:45 vectr0n.json

**Comment by vectr0n** [comment]
Upon further inspection it seems to just be pm2 causing an issue for me, even with updating it to run ``lounge start``. When running it outside of pm2, works just fine. I will have to take a look into pm2 at a later time, screen will do fine for now. Sorry to bother anyone.

**Comment by pallavagarwal07** [comment]
Hi,
I'll try to explain it best I can, but this problem occurred with our deployment even without restarting.
Our deployment was installed and started on 8th March and was working fine upto 11th March when the above mentioned error started popping up.
```
2017-03-11 02:11:17 [ERROR] Failed to read user config { Error: ENOENT: no such file or directory, open '/home/ubuntu/.lounge/users/.anantp.swp.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at ClientManager.readUserConfig (/usr/lib/node_modules/thelounge/src/clientManager.js:148:16)
    at ClientManager.loadUser (/usr/lib/node_modules/thelounge/src/clientManager.js:55:15)
    at _.difference.forEach.name (/usr/lib/node_modules/thelounge/src/clientManager.js:38:59)
    at Array.forEach (native)
    at FSWatcher.fs.watch._.debounce (/usr/lib/node_modules/thelounge/src/clientManager.js:38:38)
    at invokeFunc (/usr/lib/node_modules/thelounge/node_modules/lodash/lodash.js:10350:23)
    at trailingEdge (/usr/lib/node_modules/thelounge/node_modules/lodash/lodash.js:10397:18)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/ubuntu/.lounge/users/.anantp.swp.json' }
```

Any new users made work fine (also without restarting the server). They can connect to networks and channels just fine.

Old users seem to have been logged out of networks (and hence channels as well) although disconnecting and connecting again works (just `/connect` **does not**)

Unless thelounge updates itself without needing a restart, I doubt this is related to the release.

**Comment by Thumpxr** [comment]
So, it occurs to me only when upgrading to 2.2.2. After a downgrade to 2.2.1 its fine.

When i open Lounge on 2.2.1, close firefox and upgrade, then restart firefox with auto reloading tabs, then i get this message:
`
The Lounge is loading…

Connection failed: Error: xhr poll error

This is taking longer than it should, there might be connectivity issues.
`
After i got the message and want to reload the page the pm2 instance seems to be errored.
Furthermore i dont have the .swp.json file...

**Comment by Thumpxr** [comment]
It seems to be an issue with pm2, not with lounge.

PM2 cant spawn a daemon because some stdio file isnt available.
Somehow funny is that when i downgrade to 2.2.1, reboot my server and do "pm2 start lounge" it works - although it works not on 2.2.2, which would imply, that its an issue with lounge...

**Comment by Thumpxr** [comment]
Workaround for me: use screen instead of pm2

**Comment by xPaw** [comment]
Looks like the temporary file gets created by some program, autoloader detects it, and by the time it is read, it no longer exists. We shouldn't​ crash in this case.

**Comment by xPaw** [comment]
So I looked over the code, does your server actually crash or it keeps working? Because that load function is  actually wrapped in a try/catch, and it prints into console as an ERROR, but the process should continue working.

**Comment by Thumpxr** [comment]
Just as an update. I retried PM2 as screen was really unstable and still cant start lounge. Although now pm2 restart 15 times lounge and then goes to "errored" state.

Does someone else have no issues? I already tried a purge of pm2, npm, lounge, etc.
Running:
ubuntu 17.04
npm 4.6.1
pm2 2.4.6
lounge v2.2.2
nodejs 7.10.0

**Comment by Thumpxr** [comment]
Well, i never told pm2 to "lounge start" .. only to "lounge", which resulted in the error due to many restarts. Resolved by "pm2 start lounge -- start" to pass the arg "start"
